server: 
  ingress: 
    enabled: true,
    ingressClassName: "nginx"
    annotations: 
      "nginx.org/mergeable-ingress-type": "minion"
    hosts: ["*.amazonaws.com"]
    paths: ["/"]
    https: false
configs: 
  params: 
    "server.insecure": true
  timeout.reconciliation: "20s"